apiVersion: v1
kind: Service
metadata:
  name: quarkus-postgre
  labels:
    app: quarkus
spec:
  ports:
    - port: 5432
  selector:
    app: quarkus
    tier: postgre
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-pv-claim
  labels:
    app: quarkus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: quarkus-postgre
  labels:
    app: quarkus
spec:
  selector:
    matchLabels:
      app: quarkus
      tier: postgre
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: quarkus
        tier: postgre
    spec:
      containers:
      - image: postgres:10.5
        imagePullPolicy: IfNotPresent
        name: postgre
        env:
        - name: POSTGRES_USER
          value: ffzs
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-pass
              key: password
        ports:
        - containerPort: 5432
          name: postgre
        volumeMounts:
        - name: postgre-persistent-storage
          mountPath: /var/lib/postgresql/data 
      volumes:
      - name: postgre-persistent-storage
        persistentVolumeClaim:
          claimName: postgre-pv-claim
